{{ if .Values.cni.enabled }}
{{ if or (eq .Values.cni.instanceVersion "v2.4") (eq .Values.cni.instanceVersion "v2.5") (eq .Values.cni.instanceVersion "v2.6") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    maistra-version: "2.6.4"
  name: {{ .Values.cni.defaultResourceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cni.defaultResourceName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cni.defaultResourceName }}
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
