{{ if .Values.cni.enabled }}
{{ if or (eq .Values.cni.instanceVersion "v2.4") (eq .Values.cni.instanceVersion "v2.5") (eq .Values.cni.instanceVersion "v2.6") }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    maistra-version: "2.6.4"
  name: {{ .Values.cni.defaultResourceName }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - 'use'
{{ end }}
{{ end }}