{{ if .Values.cni.enabled }}
{{ if or (eq .Values.cni.instanceVersion "v2.4") (eq .Values.cni.instanceVersion "v2.5") (eq .Values.cni.instanceVersion "v2.6") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    maistra-version: "2.6.5"
  name: {{ .Values.cni.defaultResourceName }}
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
